spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/aqua_note?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: sunli
    driver-class-name: com.mysql.cj.jdbc.Driver
  
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.clematis.aquanote.pojo
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

logging:
  level:
    top.clematis.aquanote: debug
    org.springframework.security: debug
